### ISSUE TITLE
No mouse on Pixel Slate

### ISSUE THREAD

**Issue by paulmorabito** [moonlight-stream/moonlight-chrome#500]
Hi,

I'm running a Pixel Slate on beta channel with latest ChromeOS build and also latest Moonlight. Am also using the official Google Slate keyboard. The issue is that the trackpad does not seem to be recognized by moonlight so within an open stream, there is no movement of the mouse. Touchscreen sometimes make the pointer appear but am unable to move the mouse or select anything.

This worked on my previous PixelBook using same ChromeOS version so it seems specific to the Slate and Google keyboard.

Any help would be very appreciated.

**Comment by flowerdealer** [comment]
I also have this issue on the beta channel with the Lenovo C330. Mouse capture is also not working correctly on the Android version.

**Comment by Fraserbc** [comment]
I'm having the same issue on a c101pa except the mouse input works fine on android

**Comment by Fraserbc** [comment]
Mouse clicks and scrolling works but movement doesn't

**Comment by flowerdealer** [comment]
For me mouse pointer completely disappears, and doesn't work, but clicking works as you point out, but it's stuck at the right corner of the screen.

**Comment by cyphercolt** [comment]
Samsung Chromebook Plus
Version 78.0.3904.92 (Official Build) beta (32-bit)

My mouse doesn't move at all with the touchpad or a USB mouse. I can "right click" and "left click" with both.

Tested with Steam, as well as running my Desktop, and a few games, unfortunately no mouse control!
Last time I had an issue with the mouse, it fixed itself with a ChromeOS update.

I can use the mouse on the Android app on my Chromebook

**Comment by cgutman** [comment]
This is a regression in Chrome 78. I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1025522

**Comment by flowerdealer** [comment]
This has supposedly been fixed in the dev channel, version 79.0.3845.45. Haven't verified that the fix works personally, though.

**Comment by flowerdealer** [comment]
Fix works for the Android client on the BETA channel. But not for the Chrome browser version.

**Comment by cgutman** [comment]
79.0.3845.45 should be in the Beta channel now according to https://omahaproxy.appspot.com/

**Comment by cyphercolt** [comment]
Chome Extension Issue is still present on my Samsung Chromebook Plus (V1)
Version 79.0.3945.42 (Official Build) beta (32-bit)

The Android app is working nicely though!

**Comment by paulmorabito** [comment]
Yes, I can confirm also that Android app is now working!

**Comment by flowerdealer** [comment]
Chrome OS Beta is updated as of today and issue is fixed too!

**Comment by cyphercolt** [comment]
Confirmed the issue is no longer occurring on my Chromebook Plus on Version:
79.0.3945.66 beta

**Comment by cgutman** [comment]
ChromeOS 79 is in stable channel, so closing this one out.
