### ISSUE TITLE
Game posters take longer than they should to load

### ISSUE THREAD

**Issue by ShadowBullet** [moonlight-stream/moonlight-chrome#99]
When loading a host for available games the game posters take longer than they should to populate the grid. It takes roughly 6 seconds to load in the games to the grid.

**Comment by raidancampbell** [comment]
Does this occur on every listing or just the first one.  In theory after the posters are loaded the first time, it's cached from then onward, and subsequent loadings are much faster.

**Comment by ShadowBullet** [comment]
It's every listing, it takes roughly 6 seconds every time. Running on Chrome MacOS Sierra Beta

**Comment by raidancampbell** [comment]
Can you show me the javascript console output after clicking a host?

**Comment by ShadowBullet** [comment]
Yeah here it is.

**Comment by ShadowBullet** [comment]
Okay it won't let me paste it, give me a sec

**Comment by ShadowBullet** [comment]
[Log.zip](https://github.com/moonlight-stream/moonlight-chrome/files/453478/Log.zip)

**Comment by raidancampbell** [comment]
I can't replicate this issue, and the log doesn't indicate any errors.  What are some of the specs of the computer you're streaming to?  RAM, SSD/HDD, CPU?

**Comment by ShadowBullet** [comment]
16GB, SSD, i7 3520M

**Comment by cgutman** [comment]
I think the app list query is the reason for the delay. We only cache the app list in memory because we don't currently support updating the app list while displaying the app grid. If you wait about 30 seconds before clicking on a host, the delay should go away.

**Comment by ShadowBullet** [comment]
Waited a minute, delay is still present.

**Comment by cgutman** [comment]
Can you upload a log of you waiting a minute and then seeing the delay?

**Comment by ShadowBullet** [comment]
Uploading a video now

**Comment by ShadowBullet** [comment]
Dropbox link to the screen recording https://dl.dropboxusercontent.com/u/105861526/Screen%20Recording%202016-09-03%20at%2012.02.43%20PM.mov

**Comment by raidancampbell** [comment]
It looks like that time is all spent on `returning storage cached box art`.  There are optimizations I can do to make this better, I'll look into it

**Comment by raidancampbell** [comment]
commit bfea4dbf5f119a1be3f120397fd1763698855de5, the latest on master, should fix this issue.  Would you mind pulling and checking it out, now that you can build and all

**Comment by ShadowBullet** [comment]
Significantly better, the apps load instantly now

**Comment by ShadowBullet** [comment]
@raidancampbell With newest commit b94e7cd the delay is preset again.

**Comment by ShadowBullet** [comment]
Only upon first loading the application, after clicking on a host, and backing out it is fast again.

**Comment by ShadowBullet** [comment]
@raidancampbell issue is still present, it loads the first box art image then takes roughly 4 more seconds to fill in the rest of the grid.
